name: Clean checkout
description: Clears workspace and checks out requested branch
runs:
  using: composite
  steps:
    - name: Cleanup workspace
      shell: bash
      run: |
        rm -rf '${{github.workspace}}'
    - name: Init
      shell: bash
      working-directory: '${{runner.workspace}}'
      run: |
        git init '${{github.workspace}}'
    - name: Add origin
      shell: bash
      working-directory: '${{github.workspace}}'
      run: |
        git remote add origin 'git@github.com:${{github.repository}}'
    - name: Checkout for PRs
      shell: bash
      working-directory: '${{github.workspace}}'
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin '${{github.sha}}'
        git checkout --force '${{github.sha}}'
        git config user.name "Actions Runner"
        git config user.email "noreply@example.com"
    - name: Checkout for branches
      shell: bash
      working-directory: '${{github.workspace}}'
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin '${{github.sha}}'
        git checkout --force '${{github.sha}}'
    - name: Update submodules
      shell: bash
      working-directory: '${{github.workspace}}'
      run: |
        git submodule sync --recursive
        git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
    - name: Fetch private actions
      shell: bash
      working-directory: '${{github.workspace}}'
      run: |
        git clone 'git@github.com:TransitApp/actions' '.github/actions'


